name: Mirror Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to mirror repo
        env:
          TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        run: |
          git remote add mirror https://x-access-token:${TOKEN}@github.com/salz808/Amen_Pray_App-017.git
          git push --mirror mirror
